common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Settings.postgresql.username %>
  password: <%= Settings.postgresql.password %>
  host: <%= Settings.postgresql.host %>

development:
  <<: *common
  database: kanban_on_rails_development

test:
  <<: *common
  database: <%= Settings.postgresql.test_database_name %>
  host: <%= Settings.postgresql.test_database_host %>

staging:
  <<: *common
  pool: 25
  database: kanban_on_rails_staging

production:
  <<: *common
  pool: 50
  database: kanban_on_rails_production
