site_url: http://localhost:3000
websockets:
  url: /cable
  domain: http://localhost:3000
mailer:
  from: info@kanbanonrails.com
  from_name: '"KanbanOnRails" <info@kanbanonrails.com>'
max_string_field_size: 255
max_text_field_size: 65536
max_column_width: 10000
production_server_deploy_host: kanbanonrails.com
git_repository: git@github.com:technoeleganceteam/kanban_on_rails.git
github_repository_url: https://github.com/technoeleganceteam/kanban_on_rails
bitbucket_base_url: https://bitbucket.com
gitlab_base_url: https://gitlab.com
postgresql:
  test_database_name: travis_ci_test
  username: postgres
  password:
secret_key_base: 66dfbcd8b3a121137d2195ae39f7d63b0e1eb9e05018b73e5e8dee29576f2f1cf2ab8c008d002547e8976eb9efd1a023054f63aa6d6247e3ec3bb49cac8b5631
secret_token: 66dfbcd8b3a121137d2195ae39f7d63b0e1eb9e05018b73e5e8dee29576f2f1cf2ab8c008d002547e8976eb9efd1a023054f63aa6d6247e3ec3bb49cac8b5631
webhook_host:  http://66432e6d.ngrok.io
devise:
  secret_key: xerwerj32n23jrtnewqwfwkosapdsmqekci4rik13jkc3bo2932njriwkpodsmdfadmasoiq32k4erwd9oewkinrgeijofemknfgrei23439i4urfnediiewnfrweinf
  pepper: 94kmdfkgngfewmfdijn1m32ewrnrm23eooooowoorn2m33333133333333efn23o2394rijnkkmlhfin2m3kefv9ojfmekwwwdvsiokslvinofep234rnfdimpoqekla
omniauth:
  github:
    id: someid
    secret: somesecret
  bitbucket:
    key: somekey
    secret: somesecret
  gitlab:
    key: somekey
    secret: somesecret
recaptcha:
  public_key: somekey
  private_key: someprivatekey
